# Generated by Django 5.2.3 on 2025-06-24 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomstore', '0004_profile_is_email_verified_alter_profile_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_email_verified',
        ),
    ]
